/* File generated by compile.py	github.com/ColdMacaroni/d100-compiler */
#include <stdio.h>
#include <stdlib.h>

/* This is set by the script */
#define TITLE "Table Name"
/* This number is set by the script */
#define DICE_NUM 2

int
main(int argc, char **argv)
{
    int i;
    int rolls[DICE_NUM];

    // Buffer for getting input
    char buf[BUFSIZ];

    // AUTOGENERATED
    const int required_dice[DICE_NUM] =  {3, 5};
    // Add the rolls provided as args to the array
    for (i = 1; i < argc && i <= DICE_NUM; i++)
    {
        rolls[i - 1] = atoi(argv[i]);
    }

    // Get the needed amount of rolls that werent provided by arguments
    for (int num_roll = i - 1; num_roll < DICE_NUM; num_roll++)
    {
        printf("d%d: ", required_dice[num_roll]);
        fgets(buf, BUFSIZ, stdin);
        rolls[num_roll] = atoi(buf);
    }

    // The following switches are generated by python
    switch(rolls[0])
{
    case 1:
        printf("Big");
        break;
    case 2:
        printf("Small");
        break;
    case 3:
        printf("Average");
        break;
    default:
        exit(1);
}
putchar(' ');
switch(rolls[1])
{
    case 1:
        printf("Boi");
        break;
    case 2:
        printf("Girl");
        break;
    case 3:
        printf("Girl");
        break;
    case 4:
        printf("Goblin");
        break;
    case 5:
        printf("something");
        break;
    default:
        exit(1);
}
    // Call this common courtesy
    putchar('\n');
    return 0;
}
