#include <stdio.h>
#include <stdlib.h>

/* This is set by the script */
#define TITLE "Something"
/* This number is set by the script */
#define DICE_NUM 2

int
main(int argc, char **argv)
{
    int i;
    int rolls[DICE_NUM];

    // AUTOGENERATED
    const int required_dice[DICE_NUM] = {3 ,4};

    // Add the rolls provided as args to the array
    for (i = 1; i < argc && i <= DICE_NUM; i++)
    {
        rolls[i - 1] = atoi(argv[i]);
    }


    // TODO: add switch for this shit, then inputs for missing D and the title /* What does this mean */
    printf("%d %d", rolls[0], rolls[1]);

    int val;

    return 0;
}
